CREATE DATABASE IF NOT EXISTS `wsa500_sales`;
USE `wsa500_sales`;

CREATE USER 'wsa500_sales'@'localhost' IDENTIFIED BY 'salesPassword';
GRANT ALL PRIVILEGES ON wsa500_sales.* TO 'wsa500_sales'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS `SalesRep` (
	`SalesRepID` INT(11) PRIMARY KEY AUTO_INCREMENT,
	`FirstName` VARCHAR(30) NULL DEFAULT NULL,
	`LastName` VARCHAR(30) NULL DEFAULT NULL,
	`Address1` VARCHAR(40) NULL DEFAULT NULL,
	`Address2` VARCHAR(40) NULL DEFAULT NULL,
	`City` VARCHAR(20) NULL DEFAULT NULL,
	`State` VARCHAR(20) NULL DEFAULT NULL,
	`Zip` VARCHAR(10) NULL DEFAULT NULL,
	`Country` VARCHAR(10) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `Time` (
	`TimeID` INT(11) PRIMARY KEY AUTO_INCREMENT,
	`Year` CHAR(4) NULL DEFAULT NULL,
	`Quarter` CHAR(1) NULL DEFAULT NULL,
	`Month` CHAR(2) NULL DEFAULT NULL,
	`Week` CHAR(1) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `Product` (
	`ProductID` INT(11) PRIMARY KEY AUTO_INCREMENT,
	`ProductName` VARCHAR(40) NULL DEFAULT NULL,
	`ProductDescription` VARCHAR(40) NULL DEFAULT NULL,
	`UnitPrice` DECIMAL(10,2) NULL DEFAULT NULL,
	`UnitCost` DECIMAL(10,2) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `Customer` (
	`CustomerID` INT(11) PRIMARY KEY AUTO_INCREMENT,
	`FirstName` VARCHAR(30) NULL DEFAULT NULL,
	`LastName` VARCHAR(30) NULL DEFAULT NULL,
	`Address1` VARCHAR(40) NULL DEFAULT NULL,
	`Address2` VARCHAR(40) NULL DEFAULT NULL,
	`City` VARCHAR(20) NULL DEFAULT NULL,
	`State` VARCHAR(20) NULL DEFAULT NULL,
	`Zip` VARCHAR(10) NULL DEFAULT NULL,
	`Country` VARCHAR(10) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS `Sales` (
	`CustomerID` INT(11) NOT NULL,
	`ProductID` INT(11) NOT NULL,
	`SalesRepID` INT(11) NOT NULL,
	`TimeID` INT(11) NOT NULL,
	`SalesAmount` DECIMAL(10,2) NULL DEFAULT NULL,
	CONSTRAINT `SALES_CUSTOMER_ID` FOREIGN KEY (`CustomerID`) REFERENCES `Customer` (`CustomerID`),
	CONSTRAINT `SALES_PRODUCT_ID` FOREIGN KEY (`ProductID`) REFERENCES `Product` (`ProductID`),
	CONSTRAINT `SALES_SALES_REP_ID` FOREIGN KEY (`SalesRepID`) REFERENCES `SalesRep` (`SalesRepID`),
	CONSTRAINT `SALES_TIME_ID` FOREIGN KEY (`TimeID`) REFERENCES `Time` (`TimeID`)
);
