//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.01 at 07:03:33 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.wsa500.server")
package com.wsa500.entity;
